### ISSUE TITLE
[Bug]: Connections tend to timeout, possibly related to large packets?

### ISSUE THREAD

**Issue by jonbarrow** [PretendoNetwork/nex-go#53]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

Lots of users are experiencing timeout related issues. It seems likely that this has 2 causes:

1. General stability issues on our end (will be addressed in a different issue)
2. Possible timeouts on large packets

This can be seen in Imora's network dumps, where the client times out when trying to request his friends list. The client does NOT send `PING` packets when getting fragmented responses from the server, which could result in a timeout? However I do somewhat find this unlikely, as Super Mario Maker has has large (often larger) fragmented packets for course world, and the friends server is set to timeout after 20 seconds of silence.

### What did you expect to happen?

Clients should not be randomly timing out

### Steps to reproduce? (OPTIONAL)

*No response*

### Any other details to share? (OPTIONAL)

*No response*

**Comment by DaniElectra** [comment]
> and the friends server is set to timeout after 20 seconds of silence

Unless the deployed server has a different configuration, the upstream repo uses the default 5 seconds timeout https://github.com/PretendoNetwork/nex-go/blob/39b2b55f08b9125154e408d1d23bea04e6db7ee3/stream_settings.go#L68

**Comment by jonbarrow** [comment]
The timeout is modified in the live server. I manually patched it to try and help Imora connect, it's set to `20000`
